language: go

go:
        - 1.5

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

script:
        - echo "-- USING OPTIMIZED ASSEMBLY --"
        - make
        - echo "-- USING A PURE-C IMPLEMENTATION --"
        - USE_C=true make clean all
        - echo "-- GENERATING LIBRARIES FOR ARM --"
        - USE_C=true make clean test-crosscompiled
        - echo "-- GENERATING BENCHMARKING APP FOR ANDROID --"
        - make clean benchmark-android
