language: go

go:
        - 1.7

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-multilib g++-multilib

script:
        - echo "-- USING OPTIMIZED ASSEMBLY --"
        - make
        - echo "-- USING A PURE-C IMPLEMENTATION --"
        - USE_C=true make clean all
        - echo "-- GENERATING TEST BINARY FOR ARM --"
        - make clean test-arm
        - echo "-- GENERATING TEST BINARY FOR INTEL EDISON --"
        - make clean test-edison
